Fixed to allow many inputmask type in between filter.
z-song/laravel-admin pull request #5328
Opened 2021-05-21 09:17 UTC by takkkken

私はビトウィーンフィルターで、integer()、decimal()、currency()　などが使えるように修正しました。
`$filter->between('amount',__('数量'))->integer();`
`$filter->between('distance',__('距離'))->decimal();`
`$filter->between('price',__('価格'))->currency();`
よろしくお願いします！

2021-05-25 03:02 UTC, jxlwqq requested changes

2021-05-26 10:36 UTC, merged

2021-05-26 11:01 UTC, ss-mokumoku commented
Laravel-Admin is a really good software. It is very helpful. Thank you.

2021-05-26 11:02 UTC, takkkken commented
Laravel-Admin is a really good software. It is very helpful. Thank you.

2021-05-26 15:08 UTC, jxlwqq commented
You're welcome.