[bug] 这里不应该写死,如果是多后台或者我后台名字不想用admin作为前缀,这里就会出现问题
z-song/laravel-admin pull request #5343
Opened 2021-06-10 08:54 UTC by ShuiPingYang

我是在使用多后台的时候发现这个问题.

2021-06-17 02:24 UTC, jxlwqq requested changes

2021-06-17 02:24 UTC, jxlwqq commented on src/Controllers/MenuController.php
> -        return redirect()->route('admin.auth.menu.edit', ['menu' => $id]);
这个是 route 别名。
详见这个方法：https://github.com/z-song/laravel-admin/blob/0ba9c9116178c8c6f2d49cfeed8c819f9a34397e/src/Admin.php#L307

2021-06-17 05:55 UTC, ShuiPingYang commented on src/Controllers/MenuController.php
> -        return redirect()->route('admin.auth.menu.edit', ['menu' => $id]);
这个我知道的,你可以试一下再加一个后台,就是多用户后台,各自的菜单需要单独管理,你都叫这个别名,是不是编辑完了b后台,菜单也跳转到了admin后台呢?因为你这个别名就限定了只能台跳转到amidn后台,虽然有个办法可以继承重写,但是我认为这里最好的办法应该是和配置文件里面定义的前缀一样.

虽然其他route也定义了admin别名,但是程序里面其他地方没有像菜单那样直接跳转,所以不会出现b菜单编辑完跳转到了a菜单的情形.

2021-06-17 07:09 UTC, ShuiPingYang commented on src/Controllers/MenuController.php
> -        return redirect()->route('admin.auth.menu.edit', ['menu' => $id]);
我录了个视频发到了你的邮箱(jxlwqq@gmail.com),你可以查看一下,如果后续需要我做某些测试,我也可以帮下忙.

2021-06-17 08:19 UTC, jxlwqq commented on src/Controllers/MenuController.php
> -        return redirect()->route('admin.auth.menu.edit', ['menu' => $id]);
主项目仓库代码不保证多后台配置的可用性。

2021-06-18 01:24 UTC, ShuiPingYang commented on src/Controllers/MenuController.php
> -        return redirect()->route('admin.auth.menu.edit', ['menu' => $id]);
> 主项目仓库代码不保证多后台配置的可用性。

但是这也是个可以改善的地方啊

2021-09-03 02:20 UTC, closed without merging